package com.qibla.muslimday.app2025.model

import android.content.Context
import com.qibla.muslimday.app2025.R

data class Allah99Name(
    var name: String? = null,
    var transliteration: String? = null,
    var meaning: String? = null,
)

val strName = """
      	ٱلرَّحْمَٰنُ,	
      	ٱلرَّحِيمُ,	
      	ٱلْمَلِكُ,	
      	ٱلْقُدُّوسُ,	
      	ٱلسَّلَامُ,	
      	ٱلْمُؤْمِنُ,	
      	ٱلْمُهَيْمِنُ,	
      	ٱلْعَزِيزُ,	
      	ٱلْجَبَّارُ,
      	ٱلْمُتَكَبِّرُ,	
      	ٱلْخَٰلِقُ,	
      	ٱلْبَارِئُ,	
      	ٱلْمُصَوِّرُ,	
      	ٱلْغَفَّارُ,	
      	ٱلْقَهَّارُ,	
      	ٱلْوَهَّابُ,	
      	ٱلْرَّزَّاقُ,	
      	ٱلْفَتَّاحُ,	
      	ٱلْعَلِيمُ,	
      	ٱلْقَابِضُ,	
      	ٱلْبَاسِطُ,	
      	ٱلْخَافِضُ,	
      	ٱلْرَّافِعُ,	
      	ٱلْمُعِزُّ,	
      	ٱلْمُذِلُّ,	
      	ٱلسَّمِيعُ,	
      	ٱلْبَصِيرُ,	
      	ٱلْحَكَمُ,	
      	ٱلْعَدْلُ,	
      	ٱللَّطِيفُ,	
      	ٱلْخَبِيرُ,	
      	ٱلْحَلِيمُ,	
      	ٱلْعَظِيمُ,	
      	ٱلْغَفُورُ,	
      	ٱلشَّكُورُ,	
      	ٱلْعَلِيُّ,	
      	ٱلْكَبِيرُ,	
      	ٱلْحَفِيظُ,	
      	ٱلْمُقيِتُ,	
      	ٱلْحَسِيبُ,	
      	ٱلْجَلِيلُ,	
      	ٱلْكَرِيمُ,	
      	ٱلْرَّقِيبُ,	
      	ٱلْمُجِيبُ,	
      	ٱلْوَاسِعُ,	
      	ٱلْحَكِيمُ,	
      	ٱلْوَدُودُ,	
      	ٱلْمَجِيدُ,	
      	ٱلْبَاعِثُ,	
      	ٱلْشَّهِيدُ,	
      	ٱلْحَقُّ,	
      	ٱلْوَكِيلُ,	
      	ٱلْقَوِيِيُ,	
      	ٱلْمَتِينُ,	
      	ٱلْوَلِيُ,	
      	ٱلْحَمِيدُ,	
      	ٱلْمُحْصِي,	
      	ٱلْمُبْدِئُ,	
      	ٱلْمُعِيدُ,	
      	ٱلْمُحْيِي,	
      	ٱلْمُمِيتُ,	
      	ٱلْحَيِّيُ,	
      	ٱلْقَيُّومُ,	
      	ٱلْوَاجِدُ,	
      	ٱلْمَاجِدُ,	
      	ٱلْوَاحِدُ,	
      	ٱلْأَحَدُ,	
      	ٱلصَّمَدُ,	
      	ٱلْقَادِرُ,	
      	ٱلْمُقْتَدِر,
      	ٱلْمُقَدِّمُ,
      	ٱلْمُؤَخِّرُ,
      	ٱلْأوَّلُ,	
      	ٱلْآخِرُ,	
      	ٱلظَّٰهِرُ,	
      	ٱلْبَاطِنُ,	
      	ٱلْوَالِي,	
      	ٱلْمُتَعَالِي,	
      	ٱلْبَرُّ,	
      	ٱلتَّوَابُ,	
      	ٱلْمُنْتَقِمُ,	
      	ٱلْعَفُوُ,	
      	ٱلْرَّؤُوفُ,	
      	مَالِكُ ٱلْمُلْكُ,	
      	ذُوالْجَلاَلِ وَالإكْرَامِ,	
      	ٱلْمُقْسِطُ,	
      	ٱلْجَامِعُ,	
      	ٱلْغَنيُّ,	
      	ٱلْمُغْنِيُ,	
      	ٱلْمَانِعُ,	
      	ٱلضَّٰرَ,	
      	ٱلنَّافِعُ,	
      	ٱلْنُورُ,	
      	ٱلْهَادِي,	
      	ٱلْبَدِيعُ,	
      	ٱلْبَاقِي,	
      	ٱلْوَارِثُ,	
      	ٱلرَّشِيدُ,	
      	ٱلصَّبُورُ,	
       
   """.trimIndent()

val strTransliteration = """
    Ar-Rahmaan,
    Ar-Raheem,
    Al-Malik,
    Al-Quddus,
    As-Salaam,
    Al-Mu’min,
    Al-Muhaymin,
    Al-Azeez,
    Al-Jabbaar,
    Al-Mutakabbir,
    Al-Khaaliq,
    Al-Baari’,
    Al-Musawwir,
    Al-Ghaffaar,
    Al-Qahhaar,
    Al-Wahhaab,
    Ar-Razzaaq,
    Al-Fattah,
    Al-‘Aleem,
    Al-Qaabid,
    Al-Baasit,
    Al-Khaafidh,
    Ar-Raafi’,
    Al-Mu’izz,
    Al-Muzil,
    As-Samee’,
    Al-Baseer,
    Al-Hakam,
    Al-‘Adl,
    Al-Lateef,
    Al-Khabeer,
    Al-Haleem,
    Al-‘Azeem,
    Al-Ghafoor,
    Ash-Shaakoor,
    Al-‘Alee,
    Al-Kabeer,
    Al-Hafeedh,
    Al-Muqeet,
    Al-Hasib,
    Al-Jaleel,
    Al-Kareem,
    Ar-Raqeeb,
    Al-Mujeeb,
    Al-Waasi’,
    Al-Hakeem,
    Al-Wadud,
    Al-Majeed,
    Al-Baa’ith,
    As-Shaheed,
    Al-Haqq	The,
    Al-Wakeel,
    Al-Qawiyy,
    Al-Mateen,
    Al-Walee,
    Al-Hameed,
    Al-Muhsee,
    Al-Mubdi’,
    Al-Mu’id,
    Al-Muhyee,
    Al-Mumeet,
    Al-Hayy	The,
    Al-Qayyoom,
    Al-Waajid,
    Al-Maajid,
    Al-Waahid,
    Al-Ahad	The,
    As-Samad,
    Al-Qaadir,
    Al-Muqtadir,
    Al-Muqaddim,
    Al-Mu’akhkhir,
    Al-Awwal,
    Al-Aakhir,
    Az-Zaahir,
    Al-Baatin,
    Al-Waalee,
    Al-Muta’ali,
    Al-Barr	The,
    At-Tawwaab,
    Al-Muntaqim,
    Al-‘Afuww,
    Ar-Ra’ooof,
    Maalik-al-Mulk,
    Thul-Jalaali wal-Ikraam,
    Al-Muqsiṭ,
    Al-Jaami’,
    Al-Ghaniyy,
    Al-Mughniyy,
    Al-Maani’,
    Ad-Dhaarr,
    An-Naafi’,
    An-Noor,
    Al-Haadi,
    Al-Badee’,
    Al-Baaqi,
    Al-Waarith,
    Ar-Rasheed,
    Al-Saboor
""".trimIndent()

fun getListMeaning(context: Context): List<String> {
    return listOf(
        context.getString(R.string.the_most_or_entirely_merciful),
        context.getString(R.string.the_bestower_of_mercy),
        context.getString(R.string.the_king_and_owner_of_dominion),
        context.getString(R.string.the_absolutely_pure),
        context.getString(R.string.the_perfection_and_giver_of_peace),
        context.getString(R.string.the_one_who_gives_emaan_and_security),
        context.getString(R.string.the_guardian),
        context.getString(R.string.the_witness),
        context.getString(R.string.the_overseer),
        context.getString(R.string.the_all_mighty),
        context.getString(R.string.the_compeller),
        context.getString(R.string.the_restorer),
        context.getString(R.string.the_supreme),
        context.getString(R.string.the_majestic),
        context.getString(R.string.the_creator),
        context.getString(R.string._the_maker),
        context.getString(R.string.the_originator),
        context.getString(R.string.the_fashioner),
        context.getString(R.string.the_all_and_oft_forgiving),
        context.getString(R.string.the_subduer),
        context.getString(R.string.the_ever_dominating),
        context.getString(R.string.the_giver_of_gifts),
        context.getString(R.string.the_provider),
        context.getString(R.string.the_opener),
        context.getString(R.string.the_judge),
        context.getString(R.string.the_all_knowing),
        context.getString(R.string._the_omniscient),
        context.getString(R.string.the_withholder),
        context.getString(R.string.the_extender),
        context.getString(R.string.the_reducer),
        context.getString(R.string.the_abaser),
        context.getString(R.string.the_exalter),
        context.getString(R.string._the_elevator),
        context.getString(R.string.the_honourer),
        context.getString(R.string.the_bestower),
        context.getString(R.string.the_dishonourer),
        context.getString(R.string.the_humiliator),
        context.getString(R.string.the_all_hearing),
        context.getString(R.string.the_all_seeing),
        context.getString(R.string.the_judge),
        context.getString(R.string._the_giver_of_justice),
        context.getString(R.string.the_utterly_just),
        context.getString(R.string.the_subtle_one),
        context.getString(R.string.the_most_gentle),
        context.getString(R.string.the_acquainted),
        context.getString(R.string.the_all_aware),
        context.getString(R.string.the_most_forbearing),
        context.getString(R.string.the_magnificent),
        context.getString(R.string.the_supreme),
        context.getString(R.string.the_forgiving),
        context.getString(R.string.the_exceedingly_forgiving),
        context.getString(R.string.the_most_appreciative),
        context.getString(R.string.the_most_high),
        context.getString(R.string._the_exalted),
        context.getString(R.string.the_greatest),
        context.getString(R.string.the_most_grand),
        context.getString(R.string.the_preserver),
        context.getString(R.string.the_all_heedful_and_all_protecting),
        context.getString(R.string.the_sustainer),
        context.getString(R.string.the_maintainer),
        context.getString(R.string.the_reckoner),
        context.getString(R.string.the_majestic),
        context.getString(R.string.the_most_generous),
        context.getString(R.string._the_most_esteemed),
        context.getString(R.string.the_watchful),
        context.getString(R.string.the_all_watchful),
        context.getString(R.string.the_responsive),
        context.getString(R.string.the_answerer),
        context.getString(R.string.the_all_encompassing),
        context.getString(R.string.the_boundless),
        context.getString(R.string.the_all_wise),
        context.getString(R.string.the_most_loving),
        context.getString(R.string.the_glorious),
        context.getString(R.string.the_most_honorable),
        context.getString(R.string.the_infuser_of_new_life),
        context.getString(R.string.the_all_observing_witnessing),
        context.getString(R.string.absolute_truth),
        context.getString(R.string.the_trustee),
        context.getString(R.string.the_disposer_of_affairs),
        context.getString(R.string.the_all_strong),
        context.getString(R.string.the_firm),
        context.getString(R.string.the_steadfast),
        context.getString(R.string.the_protecting_associate),
        context.getString(R.string.the_praiseworthy),
        context.getString(R.string.the_all_enumerating),
        context.getString(R.string.the_counter),
        context.getString(R.string.the_originator),
        context.getString(R.string.the_initiator),
        context.getString(R.string.the_restorer),
        context.getString(R.string.the_reinstater),
        context.getString(R.string.the_giver_of_life),
        context.getString(R.string.the_creator_of_death),
        context.getString(R.string.ever_living),
        context.getString(R.string.the_sustainer),
        context.getString(R.string.the_self_subsisting),
        context.getString(R.string.the_perceiver),
        context.getString(R.string.the_illustrious),
        context.getString(R.string.the_magnificent),
        context.getString(R.string.the_one),
        context.getString(R.string.the_indivisible),
        context.getString(R.string.unique),
        context.getString(R.string.the_only_one),
        context.getString(R.string.the_eternal),
        context.getString(R.string.satisfier_of_needs),
        context.getString(R.string.the_omnipotent),
        context.getString(R.string.the_powerful),
        context.getString(R.string.the_expediter),
        context.getString(R.string.the_promoter),
        context.getString(R.string.the_delayer),
        context.getString(R.string.the_first),
        context.getString(R.string.the_last),
        context.getString(R.string.the_utmost),
        context.getString(R.string.the_manifest),
        context.getString(R.string.the_all_surpassing),
        context.getString(R.string.the_hidden_one),
        context.getString(R.string.knower_of_the_hidden),
        context.getString(R.string.the_sole_governor),
        context.getString(R.string.the_self_exalted),
        context.getString(R.string.source_of_all_goodness),
        context.getString(R.string.the_ever_pardoning),
        context.getString(R.string.the_avenger),
        context.getString(R.string.the_pardoner),
        context.getString(R.string.the_most_kind),
        context.getString(R.string.master_of_the_dominion),
        context.getString(R.string.owner_of_the_kingdom),
        context.getString(R.string.possessor_of_glory_and_honour),
        context.getString(R.string.the_just_one),
        context.getString(R.string.the_gatherer),
        context.getString(R.string.the_uniter),
        context.getString(R.string.the_self_sufficient),
        context.getString(R.string.the_wealthy),
        context.getString(R.string.the_enricher),
        context.getString(R.string.the_withholder),
        context.getString(R.string.the_distresser),
        context.getString(R.string.the_propitious),
        context.getString(R.string.the_benefactor),
        context.getString(R.string.the_light),
        context.getString(R.string.the_guide),
        context.getString(R.string.the_incomparable_originator),
        context.getString(R.string.the_ever_lasting),
        context.getString(R.string.the_inheritor),
        context.getString(R.string.the_guide_to_the_right_path),
        context.getString(R.string.the_patient)
    )
}

fun getListAllah99Name(context: Context): List<Allah99Name> {
    val names = strName.split(",")
    val means = getListMeaning(context)
    val transliterations = strTransliteration.split(",")

    val list: MutableList<Allah99Name> = arrayListOf()

    for (i in 0 until 99) {
        list.add(
            Allah99Name(
                name = names[i],
                meaning = means[i],
                transliteration = transliterations[i]
            )
        )
    }

    return list
}